name: iccad_challenge_2024
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pytorch=2.1.1 
  - torchvision 
  - pytorch-cuda=12.1
  - gperf
  - flex
  - bison
  - pip:
    - jsonlines
    - accelerate==0.24.1
    - pandas 
    - fire 
    - transformers[torch]==4.35.0
    - peft==0.6.1
    - bitsandbytes==0.41.2.post2
    - scipy
    - sentencepiece 
    - transformers[dev]
    - setuptools==69.5.1
    - deepspeed==0.12.2
    - transformers[deepspeed]
    - datasketch==1.6.4
